package echo

import (
	"net/http"
	"strings"

	"github.com/labstack/echo/v4"
)

// WithEchoSwagger sets up Swagger UI routes on an Echo instance.
//
// This function configures Swagger UI with the provided options and registers
// the necessary routes on the Echo instance.
//
// Example:
//
//	e := echo.New()
//	echo.WithEchoSwagger(e,
//	    echo.WithSwaggerEnabled(true),
//	    echo.WithSwaggerInfo(&echo.SwaggerInfo{
//	        Title:       "My API",
//	        Description: "API documentation",
//	        Version:     "1.0",
//	    }),
//	    echo.WithSwaggerAuth(&echo.SwaggerAuth{
//	        Type:        "Bearer",
//	        Description: "JWT token",
//	        Name:        "Authorization",
//	        In:          "header",
//	    }),
//	)
//
// Security:
// - Swagger UI is disabled by default for security
// - Only enable in development or behind authentication
// - Use WithSwaggerAuth to add authentication for Swagger UI
//
// The function registers the following routes:
// - {path} - Swagger UI HTML page (default: /swagger/*)
// - /swagger/doc.json - OpenAPI/Swagger JSON specification (if docs package exists)
func WithEchoSwagger(e *echo.Echo, opts ...SwaggerOption) {
	settings := &swaggerSettings{
		enabled: false,
		path:    "/swagger/*",
		info:    DefaultSwaggerInfo,
	}

	// Apply options
	for _, opt := range opts {
		opt(settings)
	}

	// Only setup routes if enabled
	if !settings.enabled {
		return
	}

	setupSwaggerRoutes(e, settings)
}

// setupSwaggerRoutes configures all necessary routes for Swagger UI.
func setupSwaggerRoutes(e *echo.Echo, settings *swaggerSettings) {
	// Strip the wildcard from path for registration
	basePath := strings.TrimSuffix(settings.path, "/*")

	// Serve Swagger UI static files
	e.GET(settings.path, swaggerUIHandler(basePath, settings))

	// Serve Swagger JSON (if docs package is available)
	// This is typically generated by swag tool
	e.GET(basePath+"/doc.json", swaggerJSONHandler(settings))
}

// swaggerUIHandler returns the Swagger UI HTML page.
func swaggerUIHandler(basePath string, settings *swaggerSettings) echo.HandlerFunc {
	return func(c echo.Context) error {
		html := generateSwaggerHTML(basePath, settings)
		c.Response().Header().Set(echo.HeaderContentType, echo.MIMETextHTMLCharsetUTF8)
		return c.HTML(http.StatusOK, html)
	}
}

// swaggerJSONHandler serves the Swagger/OpenAPI JSON specification.
func swaggerJSONHandler(settings *swaggerSettings) echo.HandlerFunc {
	return func(c echo.Context) error {
		// Try to serve from docs package if available
		// This will return 404 if docs package doesn't exist
		return c.JSON(http.StatusOK, map[string]interface{}{
			"swagger": "2.0",
			"info": map[string]interface{}{
				"title":       settings.info.Title,
				"description": settings.info.Description,
				"version":     settings.info.Version,
			},
			"paths": map[string]interface{}{},
		})
	}
}

// generateSwaggerHTML generates the Swagger UI HTML page with configuration.
func generateSwaggerHTML(basePath string, settings *swaggerSettings) string {
	authConfig := ""
	if settings.auth != nil {
		authConfig = generateAuthConfig(settings.auth)
	}

	return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>` + settings.info.Title + `</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin: 0; padding: 0; font-family: "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
        .topbar { display: none; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js" charset="UTF-8"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js" charset="UTF-8"></script>
    <script>
        window.onload = function() {
            const ui = SwaggerUIBundle({
                url: "` + basePath + `/doc.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout",
                defaultModelsExpandDepth: 1,
                defaultModelExpandDepth: 1,
                docExpansion: "list",
` + authConfig + `
            });
            window.ui = ui;
        };
    </script>
</body>
</html>`
}

// generateAuthConfig generates JavaScript configuration for Swagger UI authentication.
func generateAuthConfig(auth *SwaggerAuth) string {
	if auth == nil {
		return "                validatorUrl: null,"
	}

	switch auth.Type {
	case "Bearer":
		return `                spec: {
                    security: [{
                        Bearer: []
                    }]
                },
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
`

	case "ApiKey":
		return `                spec: {
                    security: [{
                        ApiKey: []
                    }]
                },
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
`

	case "Basic":
		return `                spec: {
                    security: [{
                        Basic: []
                    }]
                },
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
`

	case "OAuth2":
		return `                spec: {
                    security: [{
                        OAuth2: []
                    }]
                },
                initOAuth: {
                    appName: "` + auth.Description + `"
                },
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
`

	default:
		return "                validatorUrl: null,"
	}
}
